### ISSUE TITLE
Add chat_id for config

### ISSUE THREAD

**Issue by ALiwoto** [Dank-del/Chizuru-GO#1]
I saw this section in config file:
```cfg
[telegram_links]
channel =
chat = 
```
these shouldn't be int64, right?
they are username and their only usage is for showing them to users, right?
isn't it better to add another value for debugging and testing purpose?
something like `chat_id`?
which should be an int64 and we have to try parsing it to int64

**Comment by Dank-del** [comment]
Not yet.

**Comment by ALiwoto** [comment]
> Not yet.

then one more thing, why it's like this here?
```go
	ChatLINK, err = p.Get("telegram_links", "chat")
	if err != nil {
		log.Fatal("an error in getting chat link: ", err)
	}
	ChannelLINK, err = p.Get("telegram_links", "channel")
	if err != nil {
		log.Fatal("an error in getting channel link: ", err)
	}
```
are they really mandatory that we have to terminate the process if we don't find them?

**Comment by Dank-del** [comment]
Imagine InlineKeyboardButton without url.

**Comment by ALiwoto** [comment]
> Imagine InlineKeyboardButton without url.

The only thing we have to do is to check if the string is empty or not, then we don't create that button in the first place.
It needs a little bit more code, but I think it will increase the usability of the program, don't you think so?

**Comment by Dank-del** [comment]
I don't wanna send /start reply without button.

**Comment by ALiwoto** [comment]
> I don't wanna send /start reply without button.

Just give me something to create a pull request for it : sob :
